Numpy is more effective than list in 3 criteria for large data set:
1. Less Memory
2. Fast
3. Covenient
4. N-dimentional Array

In [ ]:
import numpy as np
import sys
import time

In [ ]:
# list size
list1 = range(1000)
list_size = (sys.getsizeof(5)*len(list1))

In [ ]:
# np array size
np_array = np.arange(1000)
np_array_size = (np_array.size*np_array.itemsize)

In [ ]:
# size difference
print(list_size)
print(np_array_size)

28000
8000


**Per list element tales 28 bytes in Python whereas per item in numoy array takes only one byte or one bit and which is also a contagious memory**

In [ ]:
size = 1_000_000
l1 = range(size)
l2 = range(size)

In [ ]:
# np_array
npa1 = np.arange(size)
npa2 = np.arange(size)

In [ ]:
# python list millon sum time
start_list = time.time()
res = [(x+y) for x,y in zip(l1,l2)]
print(f'python list took {(time.time() - start_list)*1000}')

python list took 210.25800704956055


In [ ]:
# np array million sum time
start_array = time.time()
res_arr = npa1 + npa2 # we can directly apply mathematical operations like addition,substraction, multiplications on np array with using list comprehension
print(f'np arrat took: {(time.time()- start_array)*1000}')

np arrat took: 9.141683578491211


**Numpy Array Basic Operations**

In [ ]:
arr1 = np.array([[1,2],[3,4],[5,6]])
# dimetion of array
print(arr1.ndim)
# size of the array meaning total items in the whole array
print(arr1.size)
# size of the each item of the array
print(arr1.itemsize)
# shape of the array/matrix or row/column
print(arr1.shape)

2
6
8
(3, 2)


In [ ]:
arr1_float = arr1.astype(float)
print(arr1_float)
print(arr1_float.itemsize)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
8


In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full((2,3),7)) # np.full((row,column),value)

[[7 7 7]
 [7 7 7]]


In [ ]:
arr2 = np.array([8,9,10,4,6,7])
arr2 = np.sort(arr2) # so
print(arr2)

[ 4  6  7  8  9 10]


In [ ]:
# reshape
new = arr2.reshape(2,3)
print(new)

[[ 4  6  7]
 [ 8  9 10]]


In [ ]:
# conversion from 1D to 2D array
# np.newaxis np.expand_dims
a = np.arange(8)
print(a.shape)

(8,)


In [ ]:
a2 = a[np.newaxis, :]
print(a2.shape)

(1, 8)


In [ ]:
a_new = np.array([[1,2,3],[4,5,6]])
print(a_new.shape)

(2, 3)


In [ ]:
a_new = a_new[np.newaxis, :]
print(a_new.shape)

(1, 2, 3)


**2D array Slicing**

In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2[0,0]) # this is how 2d indexing works

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1


In [ ]:
# 2d slicing
print(arr2[0,1:4]) # we can use slicing in both indexes
print(arr2[:2,1:4])

[2 3 4]
[[2 3 4]
 [7 8 9]]


**Numpy Universal Function**

In [ ]:
arra = np.array([1,2,3,4,5,6,7,8,9])

print(np.sqrt(arra))
print(np.absolute(arra))
print(np.sign(arra)) # will return -1 for negative values, 0 for 0 and 1 for positive values
print(np.exp(arra))
print(np.sin(arra)) # trigonomery
print(np.max(arra))
print(np.min(arra))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
9
1


**View vs Copy**

In [ ]:
arr4 = np.arange(10)
print(arr4)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr5 = arr4
print(arr5)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr4[0] = 100
print(arr5)

[100   1   2   3   4   5   6   7   8   9]


In [ ]:
arr6 = arr4.view()
print(arr6) # so the view is actually referencing the same object after copying the whole. it is called shallow copy
# all of the three will have the same refrence
arr4[1] = 101
print(arr4)
print(arr6)

[100   1   2   3   4   5   6   7   8   9]
[100 101   2   3   4   5   6   7   8   9]
[100 101   2   3   4   5   6   7   8   9]


In [ ]:
# copy creates a new instance which is called a deep copy with a separate data buffer.
arr7 = arr4.copy()
print(arr7)

[100 101   2   3   4   5   6   7   8   9]


In [ ]:
arr4[2] = 102
print(arr4)
print(arr7)

[100 101 102   3   4   5   6   7   8   9]
[100 101   2   3   4   5   6   7   8   9]


**Shape and Reshape**

In [ ]:
arr8 = np.arange(12)
print(arr8.shape)

(12,)


In [ ]:
# converting 1D to 2D
arr8 = arr8.reshape(3,4)
print(arr8)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# converi=ting into 3D
arr8 = arr8.reshape(3,2,2)
print(arr8)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [ ]:
# flattening
arr8 = arr8.reshape(-1)
print(arr8)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


**Iterating through numopy array**

In [ ]:
one_d = np.arange(10)

for item in one_d:
  print(item)

0
1
2
3
4
5
6
7
8
9


In [ ]:
two_d = np.array([[1,2,3,4],[5,6,7,8]])
for row in two_d:
  for item in row:
    print(item)

1
2
3
4
5
6
7
8


In [ ]:
three_d = np.array([[[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]])
for dimention in three_d:
  for row in dimention:
    for item in row:
      print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# simple way to iterate through each item in nd array
for item in np.nditer(three_d):
  print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# use np.sort to sort numpy array items without changing the actual array

In [ ]:
search = np.array([1,2,3,3,4,4,4,3,2,9])
x = np.where(search == 2) # this will return a tuple of the index of matching numbers
print(x)

(array([1, 8]),)


In [ ]:
print(x[0])

[1 8]


In [ ]:
y = np.where(search % 2 == 0)
print(y)

(array([1, 4, 5, 6, 8]),)


**Filter**

In [ ]:
array1 = np.arange(12)

filter = [ True if item % 2 == 0 else False for item in array1 ]
print(filter)

[True, False, True, False, True, False, True, False, True, False, True, False]


In [ ]:
print(array1[filter])
# shortcut for similar work
filter2 = array1 % 2 == 0
print(array1[filter2])

[ 0  2  4  6  8 10]
[ 0  2  4  6  8 10]
